env:
  browser: true
  # Allow use of dynamic import() and import.meta
  es2020: true
  node: true
  webextensions: true
extends:
  - google
  - "eslint:recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  sourceType: module
rules:
  guard-for-in: off
  indent:
    - error
    - 2
    - ignoredNodes:
      - TemplateLiteral > *
