env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  arrow-parens:
    - error
    - as-needed
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style: off
  object-curly-spacing:
    - error
    - always
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
