env:
  browser: true
  commonjs: true
  es6: true
  node: true
  webextensions: true
extends:
  - google
  - "eslint:recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 2
    - ignoredNodes:
      - TemplateLiteral > *
