env:
  browser: true
  es2020: true
  node: true
  webextensions: true
extends:
  - 'eslint:recommended'
  - google
  - 'plugin:prettier/recommended'
ignorePatterns:
  - '**/__snapshots__/**'
  - '**/vendor/**'
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules: {}
