language: node_js
node_js:
  - lts/*

env:
  - CHROME_APP_ID=cnglbnilhbknecgmekgagelljoljcbfe

deploy:
  provider: script
  script: npm run build && bash deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    tags: false