/**
 * @file Provides paths and loaders for JSON schemas used throughout this
 * project.
 */

import { promises as fsPromises } from "fs";
import { dirname, resolve as resolvePath } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const { readFile } = fsPromises;

/**
 * Type of the JSON schema object for `hots.json`
 * @typedef {import("../docs/hots-schema.json")} HotsSchema
 */

/**
 * Type of the JSON schema object for hero data JSON files generated by
 * HeroesDataParser
 * @typedef {import("../docs/hdp-herodata-schema.json")} HdpHeroDataSchema
 */

/**
 * Absolute path of the JSON schema for `hots.json`.
 */
export const HOTS_SCHEMA_PATH = resolvePath(
  __dirname,
  "../docs/hots-schema.json"
);

/**
 * Absolute path of the JSON schema for `herodata_*_enus.json` files, generated
 * by HeroesDataParser.
 */
export const HDP_HERODATA_SCHEMA_PATH = resolvePath(
  __dirname,
  "../docs/hdp-herodata-schema.json"
);

/**
 * Loads the JSON schema for `hots.json`.
 * @return {Promise<HotsSchema>}
 */
export async function loadHotsSchema() {
  return JSON.parse(await readFile(HOTS_SCHEMA_PATH, "utf8"));
}

/**
 * Loads the JSON schema for `hots.json`.
 * @return {Promise<HdpHeroDataSchema>}
 */
export async function loadHdpHeroDataSchema() {
  return JSON.parse(await readFile(HDP_HERODATA_SCHEMA_PATH, "utf8"));
}
